import type { Metadata } from "next";
import localFont from "next/font/local";
import { Providers } from "./components/providers";
import "./globals.css";
import Appbar from "./components/Appbar";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "WhiteBoard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {
  // Fetch the session data
 

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Pass the session data to the SessionProvider */}
        <Providers>
          <Appbar/>
            {children}</Providers>
         
       
      </body>
    </html>
  );
}
