import type { Metadata } from "next";

import { Providers } from "./components/providers";
import "./globals.css";
import Appbar from "./components/Appbar";



export const metadata: Metadata = {
  title: "WhiteBoard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {
  // Fetch the session data
 

  return (
    <html lang="en">
      <body
        
      >
        {/* Pass the session data to the SessionProvider */}
        <Providers>
          <Appbar/>
            {children}</Providers>
         
       
      </body>
    </html>
  );
}
